### In-class exercise for Tue, 2017-04-12.  If submitted by midnight, Thu, April 13th, you will earn 3 participation credits.

In [187]:
import numpy as np
import pandas as pd

## 1. Solve the following system of equations:

x1 + 2\*x2 = 7
-x2 + x3 = 6
x1 - 4\*x2 + x3 = -2

Use linear algebra (feel free to check your LA result with other methods if you have nothing better to do ;-) 


In [188]:
a = np.array([[1,2,0], [0,-1, 1], [1, -4, 1]])
b = np.array([7,6,-2])
x = np.linalg.solve(a, b)
x

array([ 1.,  3.,  9.])

## 2. Condition number
Read the AmesHousing dataset documentation.  It is sales price data for Ames, IA, the variable 'SalePrice' represents the sale price in USD.  We are working toward predicting the price based on the observed features.  (but we don't get that far...)

Determine the data type and import this data into python.  Ensure you imported it correctly.

Looking at the documentation, the sale price ($$) is a continuous variable.

In [189]:
df = pd.read_csv('ameshousing.csv', sep='\t', lineterminator='\n')

In [190]:
print ('Shape :', df.shape)
print ('Columns:\n', df.columns)
print ('Data Types:\n',df.dtypes)

df.head()

Shape : (2930, 82)
Columns:
 Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage T

Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      1  526301100           20        RL         141.0     31770   Pave   
1      2  526350040           20        RH          80.0     11622   Pave   
2      3  526351010           20        RL          81.0     14267   Pave   
3      4  526353030           20        RL          93.0     11160   Pave   
4      5  527105010           60        RL          74.0     13830   Pave   

  Alley Lot Shape Land Contour     ...      Pool Area Pool QC  Fence  \
0   NaN       IR1          Lvl     ...              0     NaN    NaN   
1   NaN       Reg          Lvl     ...              0     NaN  MnPrv   
2   NaN       IR1          Lvl     ...              0     NaN    NaN   
3   NaN       Reg          Lvl     ...              0     NaN    NaN   
4   NaN       IR1          Lvl     ...              0     NaN  MnPrv   

  Misc Feature Misc Val Mo Sold Yr Sold Sale Type  Sale Condition  SalePrice\r  
0          NaN        0       5    2010       WD           Normal       215000  
1          NaN        0       6    2010       WD           Normal       105000  
2         Gar2    12500       6    2010       WD           Normal       172000  
3          NaN        0       4    2010       WD           Normal       244000  
4          NaN        0       3    2010       WD           Normal       189900  

[5 rows x 82 columns]

**2.1** The dataset includes a large number of variables.  Some of these are numeric (continuous), some are categoric (nominal) and others are ordered (ordinal).  However, many statistical methods can only handle numeric variables.

Look at variable 'Street'.  Is it numeric, categorical, or ordered?

In [191]:
type(df.Street) #pandas Series
print(df.Street.unique())

['Pave' 'Grvl']


The Street variable is a categorical (nominal) variable.The documentation mentions that 'Street' is a nominal variable as well.

**2.2** A standard approach to handle categorical variables is to create *dummies* out of these.  This can be achieved by 'pd.get_dummies()' function.  Transform 'Street' into dummies.  How many of these do you need in your calculations?

In [192]:
street_dummies = pd.get_dummies(df.Street)
print('\n Street is a NOMINAL variable has ', len(street_dummies.columns), ' levels.')
print('\n Dataframe with Street dummies \n', street_dummies.head())


 Street is a NOMINAL variable has  2  levels.

 Dataframe with Street dummies 
    Grvl  Pave
0     0     1
1     0     1
2     0     1
3     0     1
4     0     1


There are 2 dummy variables generated for the categorical column 'Street' because it has 2 levels. We only need at most 1 dummy variable in our calculations because we can infer the state of the original categorical variable with n levels with (n-1) level bits.

**2.3** The statistical methods typically require to be fed the *design matrix*, a matrix that includes only numeric vectors for each observation.  In case of categorical features, the design matrix will contain the corresponding rows of dummies.  Create the design matrix of the 'Street' variable.  You may use 'pd.DataFrame.as_matrix()' function.

In [193]:
print('\nDesign Matrix with One Feature (Street)')
street_matrix = pd.DataFrame.as_matrix(street_dummies)
design_matrix = street_matrix  
design_matrix


Design Matrix with One Feature (Street)


array([[0, 1],
       [0, 1],
       [0, 1],
       ..., 
       [0, 1],
       [0, 1],
       [0, 1]], dtype=uint8)

**2.4** Select another feature and add to the design matrix.  If you select a categorical one, it should be converted to dummies as above.  If it is numeric, you may take it as-is.  Ordered features may be transformed to ordered numbers (such as 1,2,3,4...).  Add the data from the new variable to your design matrix.  You may use 'numpy.hstack()' to concatenate matrices column-wise.


In [194]:

heat_dummies = pd.get_dummies(df.Heating)
print('\n Heating is a NOMINAL variable with ', len(heat_dummies.columns), ' levels.')
print('\n Dataframe with Heating dummies \n', heat_dummies.head())

heat_matrix = pd.DataFrame.as_matrix(heat_dummies)


 Heating is a NOMINAL variable with  6  levels.

 Dataframe with Heating dummies 
    Floor  GasA  GasW  Grav  OthW  Wall
0      0     1     0     0     0     0
1      0     1     0     0     0     0
2      0     1     0     0     0     0
3      0     1     0     0     0     0
4      0     1     0     0     0     0


In [195]:
#Create Design Matrix 
design_matrix = np.hstack((street_matrix, heat_matrix))
print('\n Design Matrix Shape =', design_matrix.shape)
print('\n Design Matrix with Two Features (Street, Heating)')
design_matrix


 Design Matrix Shape = (2930, 8)

 Design Matrix with Two Features (Street, Heating)


array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ..., 
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=uint8)

#### Creating Functions for repeatability

In [196]:
#Future Functions
def create_feature_matrix (df, colname_str, col_type):
    dummies = pd.get_dummies(df[colname_str])
    
    print('\n ', colname_str,' is a ',col_type, ' variable with ', len(dummies.columns), ' levels.')
    print('\n Dataframe with ', colname_str ,' dummies \n', dummies.head())
    matrix = pd.DataFrame.as_matrix(dummies)
    return matrix


#This function needs to be edited

def create_design_matrix(matrix_list):
    n = len(matrix_list) 
    if(n<2):
        return []
    else:        
        mat = matrix_list
        for mat in matrix_list:
            design_matrix = np.hstack((design_matrix, heat_matrix))
            print('\n Design Matrix Shape =', design_matrix.shape)
        return design_matrix    

**2.5** Is this matrix (near) singular?  Which variables (if any) cause
the singularity?  Proceed like this:

a) take the first column from your design matrix.  You will have nx1 matrix. 
b) compute the condition number of it  (you may use 'np.linalg.cond()').
c) print it
d) add the next column and proceed to b)

Now look how the condition number changes when you add the columns.  When it jump substantially, you have added a significant bit of multicollinearity into your design matrix.  However, condition numbers up to thousands is usually not a problem.

Add 1-2 additional variables to your design matrix and repeat the process.

In [197]:
def calculate_singularity(dm):
    #input is a feature matrix (df.as_matrix)
    nrows, ncols = dm.shape
    print('\n Calculating Singularity')
    print('\n -----------------------')
    print('\n Shape of Input Design Matrix :', nrows, ncols)
    X = np.asmatrix(dm)
    for i in range(1, ncols+1):
        cond_num = np.linalg.cond(X[:, 0:i]) 
        if (cond_num < 10000):
            print('With ', i, ' columns, condition number is ', cond_num)
        else:
            print('With ', i, ' columns, condition number is ', cond_num, '   <--- SINGULARITY')


In [198]:
#Calculate Sigularity for current design matrix
calculate_singularity(design_matrix)


 Calculating Singularity

 -----------------------

 Shape of Input Design Matrix : 2930 8
With  1  columns, condition number is  1.0
With  2  columns, condition number is  15.5938021876
With  3  columns, condition number is  54.027780157
With  4  columns, condition number is  76.9120230611
With  5  columns, condition number is  78.8232053662
With  6  columns, condition number is  85.2484931901
With  7  columns, condition number is  95.0874309763
With  8  columns, condition number is  2.5029639136e+15    <--- SINGULARITY


- Explanation (Street + Heating)

Singularity is achieved when the 8th column of Design Matrix is added! (Value = Wall from Heating)


#### Adding Kitchen Quality [Kitchen Qual]

In [199]:
kit_qual_matrix = create_feature_matrix(df, 'Kitchen Qual', 'ORDINAL')

print('\n Design Matrix with Two Features (Street, Kitchen Quality)')
design_matrix =  np.hstack((street_matrix, kit_qual_matrix))
print(design_matrix)

calculate_singularity(design_matrix)


  Kitchen Qual  is a  ORDINAL  variable with  5  levels.

 Dataframe with  Kitchen Qual  dummies 
    Ex  Fa  Gd  Po  TA
0   0   0   0   0   1
1   0   0   0   0   1
2   0   0   1   0   0
3   1   0   0   0   0
4   0   0   0   0   1

 Design Matrix with Two Features (Street, Kitchen Quality)
[[0 1 0 ..., 0 0 1]
 [0 1 0 ..., 0 0 1]
 [0 1 0 ..., 1 0 0]
 ..., 
 [0 1 0 ..., 0 0 1]
 [0 1 0 ..., 0 0 1]
 [0 1 0 ..., 0 0 1]]

 Calculating Singularity

 -----------------------

 Shape of Input Design Matrix : 2930 7
With  1  columns, condition number is  1.0
With  2  columns, condition number is  15.5938021876
With  3  columns, condition number is  15.6349042862
With  4  columns, condition number is  15.6856422148
With  5  columns, condition number is  17.1442069404
With  6  columns, condition number is  59.2290899975
With  7  columns, condition number is  4.66361664563e+14    <--- SINGULARITY


- Explanation (Street + Kitchen Quality) :
Singularity is achieved when the 7th column of Design Matrix is added! (Variable = TA 'Typical/Average' from Kitchen Quality)

#### Adding Sale Type (NOMINAL)

In [200]:
sale_type_matrix = create_feature_matrix(df, 'Sale Type', 'NOMINAL' )

print('\n Design Matrix with Two Features (Street, Sale Type)')
design_matrix =  np.hstack((street_matrix, sale_type_matrix))
print(design_matrix)

calculate_singularity(design_matrix)


  Sale Type  is a  NOMINAL  variable with  10  levels.

 Dataframe with  Sale Type  dummies 
    COD  CWD  Con  ConLD  ConLI  ConLw  New  Oth  VWD  WD 
0    0    0    0      0      0      0    0    0    0    1
1    0    0    0      0      0      0    0    0    0    1
2    0    0    0      0      0      0    0    0    0    1
3    0    0    0      0      0      0    0    0    0    1
4    0    0    0      0      0      0    0    0    0    1

 Design Matrix with Two Features (Street, Sale Type)
[[0 1 0 ..., 0 0 1]
 [0 1 0 ..., 0 0 1]
 [0 1 0 ..., 0 0 1]
 ..., 
 [0 1 0 ..., 0 0 1]
 [0 1 0 ..., 0 0 1]
 [0 1 0 ..., 0 0 1]]

 Calculating Singularity

 -----------------------

 Shape of Input Design Matrix : 2930 12
With  1  columns, condition number is  1.0
With  2  columns, condition number is  15.5938021876
With  3  columns, condition number is  15.6009377211
With  4  columns, condition number is  15.6345461467
With  5  columns, condition number is  24.1907160756
With  6  columns, condition

- Explanation:

The WD Column is creating the singularity from Sale Type is causing Singularity!