In [5]:
print ("Hello World!")

Hello World!


In [19]:
""""Write comments like this
The integers are 64 bit by default in Python, as opposed to 32 in Java."""


#Lists
favourites = []

#Create dictionary that hosts squares of numbers from 0 to 10
def bar():
    
    square_dict = {}

    for num in range(1, 10):
        square_dict.update({num: num*num})
    
    return square_dict    



In [16]:
#List comprehension
#Put for inside list brackets

a=[i for i in range(1,10)]
print(a)

b=[i*i for i in range(1,10)]
print(b)

c={i: i*i for i in range (1,10)}
print(c)

d = dict([ (i, i*i) for i in range(1,10) ])
print(d)

def foo(n):
    return  {i: i*i for i in range(10)}

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


In [23]:
#Can Time things implicitly in python using timeit
#DICT Comprehension is the fastest

#%timeit foo(10)

#%timeit dict([ (i, i*i) for i in range(1,10) ])

#% timeit bar()

%timeit {i: i*i for i in range (1,10)}



1000000 loops, best of 3: 1.76 µs per loop


# Introduction to numpy

In [24]:
import numpy as np

In [25]:
np.array([1,2,3])

array([1, 2, 3])

In [29]:
a= np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a.shape

(2, 3)

In [31]:
a.shape[0]

2

In [32]:
a.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
a.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a[0,0] #First row, First column

1

In [36]:
a[0,:] #First row, all cols

array([1, 2, 3])

In [38]:
a = np.array(range(24)).reshape(4,6)

In [39]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [40]:
a[:, 2:5] # 3rd, 4th 5th columns

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [41]:
a[(0,2), (0,3)] 
#take two elements 0,0 and 2,3 and...
#print all elements until them in an array

array([ 0, 15])

In [42]:
#Universal operations
a+2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [43]:
np.sqrt(a+2)

array([[ 1.41421356,  1.73205081,  2.        ,  2.23606798,  2.44948974,
         2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479,  3.46410162,
         3.60555128],
       [ 3.74165739,  3.87298335,  4.        ,  4.12310563,  4.24264069,
         4.35889894],
       [ 4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
         5.        ]])

In [45]:
def loop():
    b=np.zeros_like(a)
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            b[i,j] =  a[i,j] + 1
    return b

In [46]:
loop()

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [49]:
%timeit loop() #Quite slow!

10000 loops, best of 3: 23.1 µs per loop


In [50]:
%timeit b = a+1  #Whoa, 25 times faster!

The slowest run took 20.17 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.16 µs per loop


# Introducing Pandas

In [51]:
import pandas as pd

In [52]:
pd.Series(range(5,10)) #The rownums are called index. i.e. 0, 1, 2, 3, 4

0    5
1    6
2    7
3    8
4    9
dtype: int32

In [53]:
pd.Series({"WA": 10, "CA" : 40, "NY" : 25, "AK" : 3 }) #here, the dict keys become the row indices

AK     3
CA    40
NY    25
WA    10
dtype: int64

In [54]:
#Dict of Series
dict= {"a" : [1,2], "b" : ["x", "y"], "c" : [True, False]}
pd.DataFrame(dict)


a  b      c
0  1  x   True
1  2  y  False

In [55]:
column_dict = { "name" : ["Xi", "Lin", "Yu", "Wen"] ,  "age" : [12, 23, 34, 45]}
pd.DataFrame(column_dict)

age name
0   12   Xi
1   23  Lin
2   34   Yu
3   45  Wen