Short exercises on linear algebra

In [2]:
import numpy as np

1. Create a few matrices and vectors.  Assign these to variables.  Compute the transposes of some of those.  You may use '.T' postfix operator (ndarray property), or .transpose() function.

In [4]:
# your code here
a = np.array([[1,2], [3,4]])
print ("a\n", a)
b = np.array([[5], [6]])
print ("b\n", b)

a
 [[1 2]
 [3 4]]
b
 [[5]
 [6]]


2. Multiple some of these matrices.  Attempt to multiply non-compatible matrices.
You may use either *np.dot(x,y)* or *x.dot(y)* construct.

In [5]:
# your code here
a.dot(b)

array([[17],
       [39]])

3. compute rank of some of the matrices.  Create matrices with full rank and with less than full rank.
'np.linalg.matrix_rank()'.  You may also create some random matrices with something like 'np.random.normal(size=(4,6))'

In [10]:
# your code here
np.linalg.matrix_rank(a)
np.linalg.matrix_rank(b)

1

In [0]:
4. Compute determinant of your matrices.  It is easy for square matrices.  You may square the non-square ones by multiplying it by it's transpose.  Compute it for full-rank and non-full-rank matrices.





In [0]:
# your code here

5. Inverse matrices.  Create a few relatively small matrices (say, no more than 6x6) and compute inverse of these.  Then multiply the inverse with the matrix itself.  Do you get the unit matrix?

Now create an almost singluar matrix and try it again.  You can adjust the degree of singularity by adding a tiny random component.  Say: 'np.ones((3,3)) + eps*np.random.uniform(size=(3,3))' where 'eps' is a small number.

Compute also the rank of these matrices

In [9]:
# your code here.
eps = 1e-3
a = np.ones((3,3)) + eps*np.random.uniform(size=(3,3))


c = np.array([[1,2], [3,4], [2,4]])

d = np.array([[1,2], [3,4], [5,6]])

np.linalg.matrix_rank(c)
np.linalg.matrix_rank(d)




2

6. Characteristic roots (eigenvalues).  Compute eigenvalue decomposition of some of your matrices.  If it is not symmetric, make it symmetric by calculating something like X'X.  Do it both for full-rank and non-full-rank matrices.  Do it also for a matrix and for it's inverse.  You may use 'np.linalg.eig()'.

Can you get back the original matrix using C' Lambda C construction?

Compute the condition numbers of your near-singular matrices above (use numpy.linal.cond).

In [25]:
## code here
X = np.random.uniform(size=(4,6))
XX = X.dot(X.T)
print "XX'\n", XX
(val, vect) = np.linalg.eig(XX)
print "values\n", val
print "vect\n", vect
C = np.matrix(vect)
print "vectors\n", C
print "C-1\n", np.linalg.inv(C)
L = np.diag(val)
print "Lambda\n", L
print "C L C'\n", C.dot(L).dot(C.T)

XX'
[[ 1.97541027  0.57675691  1.31238481  1.12830251]
 [ 0.57675691  2.25235545  2.26088858  1.30630402]
 [ 1.31238481  2.26088858  2.90017033  1.99444153]
 [ 1.12830251  1.30630402  1.99444153  2.13405622]]
values
[ 6.86802978  1.59326422  0.6827307   0.11796758]
vect
[[ 0.34087484  0.8083904  -0.43935084  0.19308067]
 [ 0.49208841 -0.53937385 -0.3537005   0.58465443]
 [ 0.63715923 -0.15274433 -0.11483379 -0.74666625]
 [ 0.48547035  0.1795828   0.81772856  0.25177084]]
vectors
[[ 0.34087484  0.8083904  -0.43935084  0.19308067]
 [ 0.49208841 -0.53937385 -0.3537005   0.58465443]
 [ 0.63715923 -0.15274433 -0.11483379 -0.74666625]
 [ 0.48547035  0.1795828   0.81772856  0.25177084]]
C-1
[[ 0.34087484  0.49208841  0.63715923  0.48547035]
 [ 0.8083904  -0.53937385 -0.15274433  0.1795828 ]
 [-0.43935084 -0.3537005  -0.11483379  0.81772856]
 [ 0.19308067  0.58465443 -0.74666625  0.25177084]]
Lambda
[[ 6.86802978  0.          0.          0.        ]
 [ 0.          1.59326422  0.          0.   